# -*- coding: utf-8 -*-
"""ver1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-dbTWekRpba7F8-jGOHQT-XhzdTGvrf
"""

a=5
b=7
c=4
x=6.3
y=a*x*x+b*x+c
print('The value of y is ',y)