# -*- coding: utf-8 -*-
"""Ver3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAmOKjBRQCz6ATVAx5_tSnKbO3FXgdGk
"""

with open('/content/ThirdVersionData.txt', 'r') as file:
    a = float(file.readline())
    b = float(file.readline())
    c = float(file.readline())
    x = float(file.readline())
y = a*x*x+b*x+c
print('The value of y is:', y)